# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish npm package

on:
  release:
    types: [published]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        # This step sets up the Node.js environment for the workflow
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build   # Ensure your package.json has a "build": "tsc" script

  publish-npm:
    needs: build-and-test # Ensure this job runs after the build job
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow reading repository contents
      id-token: write # Required for npm publish with provenance

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish this npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build   # Rebuild to ensure dist/ exists in this job

      - name: Publish to npm
        run: npm publish --provenance --access public 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # Auth to npm
      # --provenance add security metadata to the package
      # --access public makes the package publicly accessible
