# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish npm package

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build # Ensure this job runs after the build job
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow reading repository contents
      id-token: write # Required for npm publish with provenance

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish this npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm publish --provenance --access public 
      # --provenance add security metadata to the package
      # --access public makes the package publicly accessible
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # Auth to npm
